import { prisma } from "@/lib/prisma";

export type PerformanceFilters = { period?: string; weekId?: string; month?: string; inspectorId?: string; city?: string; facilityTypeId?: string; status?: string; sensitivity?: string; reportStatus?: string; q?: string; sort?: string; dir?: string; };
export type InspectorPerformance = { id: string; name: string; employeeNumber: string; department: string; assignedTasks: number; completedTasks: number; inProgressTasks: number; lateTasks: number; completionRate: number; approvedReports: number; incompleteReports: number; avgCompliance: number; nonCompliantItems: number; notesCount: number; attachmentsCount: number; avgInspectionHours: number; avgReportIssueHours: number; draftSaves: number; reportEdits: number; failedVerifications: number; lastActivity: Date | null; documentationQuality: number; operationalCommitment: number; productivity: number; regulatoryEffectiveness: number; overallScore: number; rating: string; ratingTone: "success" | "warning" | "danger" | "security"; cities: string[]; facilityTypes: string[]; commonNotes: { text: string; count: number }[]; weeklyTrend: { name: string; value: number }[]; };

const weights = { productivity: 0.3, documentationQuality: 0.3, operationalCommitment: 0.25, regulatoryEffectiveness: 0.15 };

export async function getPerformanceContext(filters: PerformanceFilters = {}) {
  const [inspectors, weeks, facilityTypes, facilities, links, reports, auditLogs] = await Promise.all([
    prisma.inspector.findMany({ where: { status: "ACTIVE" }, orderBy: { name: "asc" } }),
    prisma.inspectionWeek.findMany({ include: { links: true }, orderBy: { startsAt: "desc" } }),
    prisma.facilityType.findMany({ where: { isActive: true }, orderBy: { name: "asc" } }),
    prisma.facility.findMany({ select: { city: true, securitySensitivity: true } }),
    prisma.weeklyLink.findMany({ include: { inspector: true, week: true, tasks: { include: { report: { include: { facility: { include: { facilityType: true } }, responses: { include: { attachments: true, checklistItem: true } }, observations: { include: { attachments: true, response: { include: { checklistItem: true } } } }, attachments: true } } } } } }),
    prisma.report.findMany({ include: { facility: { include: { facilityType: true } }, task: { include: { link: { include: { inspector: true, week: true } } } }, responses: { include: { attachments: true, checklistItem: true } }, observations: { include: { attachments: true, response: { include: { checklistItem: true } } } }, attachments: true } }),
    prisma.auditLog.findMany({ orderBy: { createdAt: "desc" } }),
  ]);
  const filteredLinks = links.filter((link) => matchesLink(link, filters));
  const filteredReports = reports.filter((report) => matchesReport(report, filters));
  const rows = inspectors.filter((inspector) => !filters.inspectorId || inspector.id === filters.inspectorId).filter((inspector) => !filters.q || `${inspector.name} ${inspector.employeeNumber}`.includes(filters.q)).map((inspector) => buildInspectorPerformance(inspector, filteredLinks, filteredReports, auditLogs));
  const sortedRows = sortRows(rows, filters.sort, filters.dir);
  return { filters, inspectors, weeks, facilityTypes, cities: unique(facilities.map((f) => f.city).filter(Boolean)), sensitivities: unique(facilities.map((f) => f.securitySensitivity).filter(Boolean)), rows: sortedRows, totals: buildTotals(sortedRows), alerts: buildAlerts(sortedRows), charts: { overall: sortedRows.map((r) => ({ name: r.name, value: r.overallScore })), productivity: sortedRows.map((r) => ({ name: r.name, value: r.productivity })), documentation: sortedRows.map((r) => ({ name: r.name, value: r.documentationQuality })), reportHours: sortedRows.map((r) => ({ name: r.name, value: r.avgReportIssueHours })), taskStatus: [{ name: "مكتملة", value: sum(sortedRows, "completedTasks") }, { name: "قيد العمل", value: sum(sortedRows, "inProgressTasks") }, { name: "متأخرة", value: sum(sortedRows, "lateTasks") }] } };
}

function buildInspectorPerformance(inspector: any, links: any[], reports: any[], auditLogs: any[]): InspectorPerformance {
  const inspectorLinks = links.filter((link) => link.inspectorId === inspector.id);
  const tasks = inspectorLinks.flatMap((link) => link.tasks);
  const inspectorReports = reports.filter((report) => report.task?.link?.inspectorId === inspector.id);
  const responses = inspectorReports.flatMap((report) => report.responses);
  const observations = inspectorReports.flatMap((report) => report.observations);
  const attachmentsCount = inspectorReports.reduce((count, report) => count + report.attachments.length + report.responses.reduce((n: number, response: any) => n + response.attachments.length, 0) + report.observations.reduce((n: number, observation: any) => n + observation.attachments.length, 0), 0);
  const assignedTasks = tasks.length;
  const completedTasks = tasks.filter((task) => task.status === "COMPLETED").length;
  const inProgressTasks = tasks.filter((task) => task.status === "IN_PROGRESS").length;
  const lateTasks = tasks.filter((task) => task.status === "LATE").length;
  const approvedReports = inspectorReports.filter((report) => report.status === "APPROVED" || report.status === "LOCKED").length;
  const incompleteReports = inspectorReports.filter((report) => report.status === "DRAFT" || report.status === "IN_PROGRESS").length;
  const nonCompliantItems = responses.filter((response) => response.evaluationStatus === "NON_COMPLIANT").length;
  const notesCount = observations.length;
  const avgCompliance = avg(inspectorReports.map((report) => report.complianceRate));
  const avgInspectionHours = avg(inspectorReports.map((report) => diffHours(report.facility?.visitDate, report.updatedAt)).filter((value) => value > 0));
  const avgReportIssueHours = avg(inspectorReports.map((report) => diffHours(report.createdAt, report.approvedAt ?? report.updatedAt)).filter((value) => value >= 0));
  const inspectorAudits = auditLogs.filter((log) => log.employeeNumber === inspector.employeeNumber || log.actorName === inspector.name);
  const draftSaves = countAudit(inspectorAudits, ["مسودة", "حفظ"]);
  const reportEdits = countAudit(inspectorAudits, ["تعديل", "تحديث"]);
  const failedVerifications = inspectorAudits.filter((log) => log.status === "FAILED" || /تحقق|verification|رمز/i.test(log.operationType + log.description)).length;
  const completionRate = ratio(completedTasks, assignedTasks);
  const documentationQuality = calcDocumentation(inspectorReports, observations, responses, attachmentsCount, reportEdits);
  const operationalCommitment = calcCommitment(completionRate, lateTasks, assignedTasks, incompleteReports, failedVerifications, inspectorReports);
  const productivity = calcProductivity(completedTasks, assignedTasks, approvedReports, avgReportIssueHours, inspectorLinks);
  const regulatoryEffectiveness = calcEffectiveness(nonCompliantItems, observations, responses);
  const overallScore = clamp(Math.round(productivity * weights.productivity + documentationQuality * weights.documentationQuality + operationalCommitment * weights.operationalCommitment + regulatoryEffectiveness * weights.regulatoryEffectiveness));
  return { id: inspector.id, name: inspector.name, employeeNumber: inspector.employeeNumber, department: inspector.department, assignedTasks, completedTasks, inProgressTasks, lateTasks, completionRate, approvedReports, incompleteReports, avgCompliance, nonCompliantItems, notesCount, attachmentsCount, avgInspectionHours, avgReportIssueHours, draftSaves, reportEdits, failedVerifications, lastActivity: latestDate([...tasks.map((t) => t.updatedAt), ...inspectorReports.map((r) => r.updatedAt), ...inspectorAudits.map((l) => l.createdAt)]), documentationQuality, operationalCommitment, productivity, regulatoryEffectiveness, overallScore, rating: ratingLabel(overallScore), ratingTone: ratingTone(overallScore), cities: unique(inspectorReports.map((r) => r.facility?.city).filter(Boolean)), facilityTypes: unique(inspectorReports.map((r) => r.facility?.facilityType?.name).filter(Boolean)), commonNotes: commonNotes(observations), weeklyTrend: buildWeeklyTrend(inspectorLinks) };
}
function matchesLink(link: any, f: PerformanceFilters) { if (f.weekId && link.weekId !== f.weekId) return false; if (f.inspectorId && link.inspectorId !== f.inspectorId) return false; if (f.month && !sameMonth(link.createdAt, f.month)) return false; if (f.period === "week" && !isRecent(link.createdAt, 7)) return false; if (f.period === "month" && !isRecent(link.createdAt, 31)) return false; return true; }
function matchesReport(report: any, f: PerformanceFilters) { if (f.inspectorId && report.task?.link?.inspectorId !== f.inspectorId) return false; if (f.weekId && report.task?.link?.weekId !== f.weekId) return false; if (f.month && !sameMonth(report.createdAt, f.month)) return false; if (f.city && report.facility?.city !== f.city) return false; if (f.facilityTypeId && report.facility?.facilityTypeId !== f.facilityTypeId) return false; if (f.sensitivity && report.facility?.securitySensitivity !== f.sensitivity) return false; if (f.reportStatus && report.status !== f.reportStatus) return false; if (f.status && report.task?.status !== f.status) return false; if (f.period === "week" && !isRecent(report.createdAt, 7)) return false; if (f.period === "month" && !isRecent(report.createdAt, 31)) return false; return true; }
function buildTotals(rows: InspectorPerformance[]) { const reports = sum(rows, "approvedReports") + sum(rows, "incompleteReports"); return { activeInspectors: rows.length, assignedTasks: sum(rows, "assignedTasks"), completedTasks: sum(rows, "completedTasks"), lateTasks: sum(rows, "lateTasks"), completionRate: ratio(sum(rows, "completedTasks"), sum(rows, "assignedTasks")), avgCompliance: avg(rows.map((r) => r.avgCompliance).filter(Boolean)), avgNotes: reports ? Math.round((sum(rows, "notesCount") / reports) * 10) / 10 : 0, avgReportIssueHours: Math.round(avg(rows.map((r) => r.avgReportIssueHours).filter(Boolean)) * 10) / 10, approvedReports: sum(rows, "approvedReports"), incompleteReports: sum(rows, "incompleteReports") }; }
function buildAlerts(rows: InspectorPerformance[]) { const alerts: { title: string; text: string; tone: "success" | "warning" | "danger" | "security" }[] = []; rows.filter((r) => r.lateTasks > 0).slice(0, 3).forEach((r) => alerts.push({ title: "مهام متأخرة", text: `${r.name} لديه ${r.lateTasks} مهمة متأخرة`, tone: "danger" })); rows.filter((r) => r.incompleteReports >= 3).slice(0, 3).forEach((r) => alerts.push({ title: "مسودات غير مكتملة", text: `${r.name} لديه ${r.incompleteReports} تقرير غير مكتمل`, tone: "warning" })); rows.filter((r) => r.documentationQuality < 60).slice(0, 3).forEach((r) => alerts.push({ title: "جودة توثيق منخفضة", text: `${r.name} يحتاج مراجعة جودة التوثيق`, tone: "warning" })); rows.filter((r) => r.completionRate < 70 && r.assignedTasks > 0).slice(0, 3).forEach((r) => alerts.push({ title: "المستهدف الأسبوعي", text: `${r.name} لم يحقق المستهدف`, tone: "danger" })); rows.filter((r) => r.failedVerifications >= 3).slice(0, 3).forEach((r) => alerts.push({ title: "تحقق فاشل متكرر", text: `${r.name} لديه محاولات تحقق فاشلة`, tone: "danger" })); rows.filter((r) => r.overallScore >= 90).slice(0, 3).forEach((r) => alerts.push({ title: "أداء ممتاز", text: `${r.name} يحقق أداء ممتازًا`, tone: "success" })); return alerts.slice(0, 8); }
function calcDocumentation(reports: any[], observations: any[], responses: any[], attachmentsCount: number, edits: number) { if (!reports.length) return 0; const nonCompliant = responses.filter((r) => r.evaluationStatus === "NON_COMPLIANT"); const notes = ratio(observations.filter((o) => (o.note ?? o.response?.inspectorNote ?? "").length >= 8).length, Math.max(1, observations.length)); const actions = ratio(observations.filter((o) => (o.correctiveAction ?? o.response?.correctiveAction ?? "").length >= 8).length, Math.max(1, observations.length)); const attachments = nonCompliant.length ? ratio(attachmentsCount, nonCompliant.length) : 100; const facility = ratio(reports.filter((r) => isFacilityComplete(r.facility)).length, reports.length); const time = ratio(reports.filter((r) => r.facility?.startedAt && r.facility?.endedAt).length, reports.length); const editsScore = edits > reports.length * 2 ? 60 : 100; return clamp(Math.round(avg([notes, actions, attachments, facility, time, editsScore]))); }
function calcCommitment(completion: number, late: number, assigned: number, incomplete: number, failed: number, reports: any[]) { return clamp(Math.round(avg([completion, assigned ? 100 - ratio(late, assigned) : 0, reports.length ? 100 - ratio(incomplete, reports.length) : 0, failed ? Math.max(0, 100 - failed * 15) : 100]))); }
function calcProductivity(done: number, assigned: number, approved: number, hours: number, links: any[]) { const target = links.reduce((total, link) => total + link.targetTasks, 0) || assigned; const timeScore = hours ? Math.max(40, 100 - Math.min(60, hours * 2)) : 75; return clamp(Math.round(avg([ratio(done, assigned), ratio(done, target), ratio(approved, Math.max(1, done)), timeScore]))); }
function calcEffectiveness(nonCompliant: number, observations: any[], responses: any[]) { const diversity = unique(observations.map((o) => o.response?.checklistItem?.mainSection).filter(Boolean)).length; return clamp(Math.round(avg([nonCompliant ? Math.min(100, 55 + nonCompliant * 8) : 55, Math.min(100, diversity * 20), ratio(responses.filter((r) => r.checklistItem?.regulatoryReference).length, Math.max(1, responses.length)), ratio(observations.filter((o) => (o.correctiveAction ?? o.response?.correctiveAction ?? "").length >= 12).length, Math.max(1, observations.length))]))); }
function buildWeeklyTrend(links: any[]) { return links.map((link) => { const total = link.tasks.length; const done = link.tasks.filter((task: any) => task.status === "COMPLETED").length; return { name: link.week?.name ?? "-", value: ratio(done, total) }; }).slice(-8); }
function commonNotes(observations: any[]) { const counts = new Map<string, number>(); observations.forEach((o) => { const text = (o.note ?? o.response?.inspectorNote ?? "").trim(); if (text) counts.set(text, (counts.get(text) ?? 0) + 1); }); return [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 5).map(([text, count]) => ({ text, count })); }
function sortRows(rows: InspectorPerformance[], sort = "overallScore", dir = "desc") { const key = sort as keyof InspectorPerformance; return [...rows].sort((a, b) => { const av = a[key] as any; const bv = b[key] as any; const result = typeof av === "string" ? av.localeCompare(String(bv), "ar") : Number(av ?? 0) - Number(bv ?? 0); return dir === "asc" ? result : -result; }); }
function isFacilityComplete(f: any) { return Boolean(f?.name && f?.location && f?.city && f?.district && f?.classification && f?.securitySensitivity && f?.representativeName && f?.contactNumber && f?.visitDate && f?.startedAt && f?.endedAt); }
function ratingLabel(score: number) { if (score >= 90) return "ممتاز"; if (score >= 80) return "جيد جدًا"; if (score >= 70) return "جيد"; if (score >= 60) return "يحتاج تحسين"; return "يحتاج متابعة"; }
function ratingTone(score: number) { if (score >= 80) return "success"; if (score >= 70) return "security"; if (score >= 60) return "warning"; return "danger"; }
function countAudit(logs: any[], words: string[]) { return logs.filter((log) => words.some((word) => `${log.operationType} ${log.description}`.includes(word))).length; }
function latestDate(values: any[]) { const dates = values.filter(Boolean).map((v) => new Date(v)).filter((d) => !Number.isNaN(d.valueOf())); return dates.length ? new Date(Math.max(...dates.map((d) => d.valueOf()))) : null; }
function sameMonth(value: Date | string, month: string) { return new Date(value).toISOString().slice(0, 7) === month; }
function isRecent(value: Date | string, days: number) { return Date.now() - new Date(value).valueOf() <= days * 24 * 60 * 60 * 1000; }
function diffHours(start?: Date | string | null, end?: Date | string | null) { if (!start || !end) return 0; return Math.max(0, (new Date(end).valueOf() - new Date(start).valueOf()) / 36e5); }
function avg(values: number[]) { const safe = values.filter((v) => Number.isFinite(v)); return safe.length ? Math.round((safe.reduce((s, v) => s + v, 0) / safe.length) * 10) / 10 : 0; }
function ratio(part: number, total: number) { return total ? clamp(Math.round((part / total) * 100)) : 0; }
function sum(rows: any[], key: string) { return rows.reduce((total, row) => total + Number(row[key] ?? 0), 0); }
function unique<T>(items: T[]) { return [...new Set(items)]; }
function clamp(value: number) { return Math.max(0, Math.min(100, value)); }