import { prisma } from "@/lib/prisma";

expor t type PerformanceFilters = { period?: string ; weekId?: string; month?: string; inspectorI d?: string; city?: string; facilityTypeId?: s tring; status?: string; sensitivity?: string;  reportStatus?: string; q?: string; sort?: st ring; dir?: string; };
export type InspectorP erformance = { id: string; name: string; empl oyeeNumber: string; department: string; assig nedTasks: number; completedTasks: number; inP rogressTasks: number; lateTasks: number; comp letionRate: number; approvedReports: number;  incompleteReports: number; avgCompliance: num ber; nonCompliantItems: number; notesCount: n umber; attachmentsCount: number; avgInspectio nHours: number; avgReportIssueHours: number;  draftSaves: number; reportEdits: number; fail edVerifications: number; lastActivity: Date |  null; documentationQuality: number; operatio nalCommitment: number; productivity: number;  regulatoryEffectiveness: number; overallScore : number; rating: string; ratingTone: "succes s" | "warning" | "danger" | "security"; citie s: string[]; facilityTypes: string[]; commonN otes: { text: string; count: number }[]; week lyTrend: { name: string; value: number }[]; } ;

const weights = { productivity: 0.3, docum entationQuality: 0.3, operationalCommitment:  0.25, regulatoryEffectiveness: 0.15 };

expor t async function getPerformanceContext(filter s: PerformanceFilters = {}) {
  const [inspec tors, weeks, facilityTypes, facilities, links , reports, auditLogs] = await Promise.all([
     prisma.inspector.findMany({ where: { statu s: "ACTIVE" }, orderBy: { name: "asc" } }),
     prisma.inspectionWeek.findMany({ orderBy:  { startsAt: "desc" } }),
    prisma.facilityT ype.findMany({ where: { isActive: true }, ord erBy: { name: "asc" } }),
    prisma.facility .findMany({ select: { city: true, securitySen sitivity: true } }),
    prisma.weeklyLink.fi ndMany({ include: { inspector: true, week: tr ue, tasks: { include: { report: { include: {  facility: { include: { facilityType: true } } , responses: { include: { attachments: true,  checklistItem: true } }, observations: { incl ude: { attachments: true, response: { include : { checklistItem: true } } } }, attachments:  true } } } } } }),
    prisma.report.findMan y({ include: { facility: { include: { facilit yType: true } }, task: { include: { link: { i nclude: { inspector: true, week: true } } } } , responses: { include: { attachments: true,  checklistItem: true } }, observations: { incl ude: { attachments: true, response: { include : { checklistItem: true } } } }, attachments:  true } }),
    prisma.auditLog.findMany({ or derBy: { createdAt: "desc" } }),
  ]);
  cons t filteredLinks = links.filter((link) => matc hesLink(link, filters));
  const filteredRepo rts = reports.filter((report) => matchesRepor t(report, filters));
  const rows = inspector s.filter((inspector) => !filters.inspectorId  || inspector.id === filters.inspectorId).filt er((inspector) => !filters.q || `${inspector. name} ${inspector.employeeNumber}`.includes(f ilters.q)).map((inspector) => buildInspectorP erformance(inspector, filteredLinks, filtered Reports, auditLogs));
  const sortedRows = so rtRows(rows, filters.sort, filters.dir);
  re turn { filters, inspectors, weeks, facilityTy pes, cities: unique(facilities.map((f) => f.c ity).filter(Boolean)), sensitivities: unique( facilities.map((f) => f.securitySensitivity). filter(Boolean)), rows: sortedRows, totals: b uildTotals(sortedRows), alerts: buildAlerts(s ortedRows), charts: { overall: sortedRows.map ((r) => ({ name: r.name, value: r.overallScor e })), productivity: sortedRows.map((r) => ({  name: r.name, value: r.productivity })), doc umentation: sortedRows.map((r) => ({ name: r. name, value: r.documentationQuality })), repo rtHours: sortedRows.map((r) => ({ name: r.nam e, value: r.avgReportIssueHours })), taskStat us: [{ name: "مكتملة", value: sum(sorte dRows, "completedTasks") }, { name: "قيد � �لعمل", value: sum(sortedRows, "inProgres sTasks") }, { name: "متأخرة", value: su m(sortedRows, "lateTasks") }] } };
}

functio n buildInspectorPerformance(inspector: any, l inks: any[], reports: any[], auditLogs: any[] ): InspectorPerformance {
  const inspectorLi nks = links.filter((link) => link.inspectorId  === inspector.id);
  const tasks = inspector Links.flatMap((link) => link.tasks);
  const  inspectorReports = reports.filter((report) =>  report.task?.link?.inspectorId === inspector .id);
  const responses = inspectorReports.fl atMap((report) => report.responses);
  const  observations = inspectorReports.flatMap((repo rt) => report.observations);
  const attachme ntsCount = inspectorReports.reduce((count, re port) => count + report.attachments.length +  report.responses.reduce((n: number, response:  any) => n + response.attachments.length, 0)  + report.observations.reduce((n: number, obse rvation: any) => n + observation.attachments. length, 0), 0);
  const assignedTasks = tasks .length;
  const completedTasks = tasks.filte r((task) => task.status === "COMPLETED").leng th;
  const inProgressTasks = tasks.filter((t ask) => task.status === "IN_PROGRESS").length ;
  const lateTasks = tasks.filter((task) =>  task.status === "LATE").length;
  const appro vedReports = inspectorReports.filter((report)  => report.status === "APPROVED" || report.st atus === "LOCKED").length;
  const incomplete Reports = inspectorReports.filter((report) =>  report.status === "DRAFT" || report.status = == "IN_PROGRESS").length;
  const nonComplian tItems = responses.filter((response) => respo nse.evaluationStatus === "NON_COMPLIANT").len gth;
  const notesCount = observations.length ;
  const avgCompliance = avg(inspectorReport s.map((report) => report.complianceRate));
   const avgInspectionHours = avg(inspectorRepor ts.map((report) => diffHours(report.facility? .visitDate, report.updatedAt)).filter((value)  => value > 0));
  const avgReportIssueHours  = avg(inspectorReports.map((report) => diffHo urs(report.createdAt, report.approvedAt ?? re port.updatedAt)).filter((value) => value >= 0 ));
  const inspectorAudits = auditLogs.filte r((log) => log.employeeNumber === inspector.e mployeeNumber || log.actorName === inspector. name);
  const draftSaves = countAudit(inspec torAudits, ["مسودة", "حفظ"]);
  const  reportEdits = countAudit(inspectorAudits, [" تعديل", "تحديث"]);
  const failedVe rifications = inspectorAudits.filter((log) =>  log.status === "FAILED" || /تحقق|verific ation|رمز/i.test(log.operationType + log.d escription)).length;
  const completionRate =  ratio(completedTasks, assignedTasks);
  cons t documentationQuality = calcDocumentation(in spectorReports, observations, responses, atta chmentsCount, reportEdits);
  const operation alCommitment = calcCommitment(completionRate,  lateTasks, assignedTasks, incompleteReports,  failedVerifications, inspectorReports);
  co nst productivity = calcProductivity(completed Tasks, assignedTasks, approvedReports, avgRep ortIssueHours, inspectorLinks);
  const regul atoryEffectiveness = calcEffectiveness(nonCom pliantItems, observations, responses);
  cons t overallScore = clamp(Math.round(productivit y * weights.productivity + documentationQuali ty * weights.documentationQuality + operation alCommitment * weights.operationalCommitment  + regulatoryEffectiveness * weights.regulator yEffectiveness));
  return { id: inspector.id , name: inspector.name, employeeNumber: inspe ctor.employeeNumber, department: inspector.de partment, assignedTasks, completedTasks, inPr ogressTasks, lateTasks, completionRate, appro vedReports, incompleteReports, avgCompliance,  nonCompliantItems, notesCount, attachmentsCo unt, avgInspectionHours, avgReportIssueHours,  draftSaves, reportEdits, failedVerifications , lastActivity: latestDate([...tasks.map((t)  => t.updatedAt), ...inspectorReports.map((r)  => r.updatedAt), ...inspectorAudits.map((l) = > l.createdAt)]), documentationQuality, opera tionalCommitment, productivity, regulatoryEff ectiveness, overallScore, rating: ratingLabel (overallScore), ratingTone: ratingTone(overal lScore), cities: unique(inspectorReports.map( (r) => r.facility?.city).filter(Boolean)), fa cilityTypes: unique(inspectorReports.map((r)  => r.facility?.facilityType?.name).filter(Boo lean)), commonNotes: commonNotes(observations ), weeklyTrend: buildWeeklyTrend(inspectorLin ks) };
}
function matchesLink(link: any, f: P erformanceFilters) { if (f.weekId && link.wee kId !== f.weekId) return false; if (f.inspect orId && link.inspectorId !== f.inspectorId) r eturn false; if (f.month && !sameMonth(link.c reatedAt, f.month)) return false; if (f.perio d === "week" && !isRecent(link.createdAt, 7))  return false; if (f.period === "month" && !i sRecent(link.createdAt, 31)) return false; re turn true; }
function matchesReport(report: a ny, f: PerformanceFilters) { if (f.inspectorI d && report.task?.link?.inspectorId !== f.ins pectorId) return false; if (f.weekId && repor t.task?.link?.weekId !== f.weekId) return fal se; if (f.month && !sameMonth(report.createdA t, f.month)) return false; if (f.city && repo rt.facility?.city !== f.city) return false; i f (f.facilityTypeId && report.facility?.facil ityTypeId !== f.facilityTypeId) return false;  if (f.sensitivity && report.facility?.securi tySensitivity !== f.sensitivity) return false ; if (f.reportStatus && report.status !== f.r eportStatus) return false; if (f.status && re port.task?.status !== f.status) return false;  if (f.period === "week" && !isRecent(report. createdAt, 7)) return false; if (f.period ===  "month" && !isRecent(report.createdAt, 31))  return false; return true; }
function buildTo tals(rows: InspectorPerformance[]) { const re ports = sum(rows, "approvedReports") + sum(ro ws, "incompleteReports"); return { activeInsp ectors: rows.length, assignedTasks: sum(rows,  "assignedTasks"), completedTasks: sum(rows,  "completedTasks"), lateTasks: sum(rows, "late Tasks"), completionRate: ratio(sum(rows, "com pletedTasks"), sum(rows, "assignedTasks")), a vgCompliance: avg(rows.map((r) => r.avgCompli ance).filter(Boolean)), avgNotes: reports ? M ath.round((sum(rows, "notesCount") / reports)  * 10) / 10 : 0, avgReportIssueHours: Math.ro und(avg(rows.map((r) => r.avgReportIssueHours ).filter(Boolean)) * 10) / 10, approvedReport s: sum(rows, "approvedReports"), incompleteRe ports: sum(rows, "incompleteReports") }; }
fu nction buildAlerts(rows: InspectorPerformance []) { const alerts: { title: string; text: st ring; tone: "success" | "warning" | "danger"  | "security" }[] = []; rows.filter((r) => r.l ateTasks > 0).slice(0, 3).forEach((r) => aler ts.push({ title: "مهام متأخرة", tex t: `${r.name} لديه ${r.lateTasks} مهم� � متأخرة`, tone: "danger" })); rows.fil ter((r) => r.incompleteReports >= 3).slice(0,  3).forEach((r) => alerts.push({ title: "مس ودات غير مكتملة", text: `${r.nam e} لديه ${r.incompleteReports} تقرير  غير مكتمل`, tone: "warning" })); row s.filter((r) => r.documentationQuality < 60). slice(0, 3).forEach((r) => alerts.push({ titl e: "جودة توثيق منخفضة", text:  `${r.name} يحتاج مراجعة جودة � �لتوثيق`, tone: "warning" })); rows.fil ter((r) => r.completionRate < 70 && r.assigne dTasks > 0).slice(0, 3).forEach((r) => alerts .push({ title: "المستهدف الأسبو عي", text: `${r.name} لم يحقق الم� �تهدف`, tone: "danger" })); rows.filter(( r) => r.failedVerifications >= 3).slice(0, 3) .forEach((r) => alerts.push({ title: "تحق� � فاشل متكرر", text: `${r.name} لد يه محاولات تحقق فاشلة`, ton e: "danger" })); rows.filter((r) => r.overall Score >= 90).slice(0, 3).forEach((r) => alert s.push({ title: "أداء ممتاز", text:  `${r.name} يحقق أداء ممتازًا`,  tone: "success" })); return alerts.slice(0,  8); }
function calcDocumentation(reports: any [], observations: any[], responses: any[], at tachmentsCount: number, edits: number) { if ( !reports.length) return 0; const nonCompliant  = responses.filter((r) => r.evaluationStatus  === "NON_COMPLIANT"); const notes = ratio(ob servations.filter((o) => (o.note ?? o.respons e?.inspectorNote ?? "").length >= 8).length,  Math.max(1, observations.length)); const acti ons = ratio(observations.filter((o) => (o.cor rectiveAction ?? o.response?.correctiveAction  ?? "").length >= 8).length, Math.max(1, obse rvations.length)); const attachments = nonCom pliant.length ? ratio(attachmentsCount, nonCo mpliant.length) : 100; const facility = ratio (reports.filter((r) => isFacilityComplete(r.f acility)).length, reports.length); const time  = ratio(reports.filter((r) => r.facility?.st artedAt && r.facility?.endedAt).length, repor ts.length); const editsScore = edits > report s.length * 2 ? 60 : 100; return clamp(Math.ro und(avg([notes, actions, attachments, facilit y, time, editsScore]))); }
function calcCommi tment(completion: number, late: number, assig ned: number, incomplete: number, failed: numb er, reports: any[]) { return clamp(Math.round (avg([completion, assigned ? 100 - ratio(late , assigned) : 0, reports.length ? 100 - ratio (incomplete, reports.length) : 0, failed ? Ma th.max(0, 100 - failed * 15) : 100]))); }
fun ction calcProductivity(done: number, assigned : number, approved: number, hours: number, li nks: any[]) { const target = links.reduce((to tal, link) => total + link.targetTasks, 0) ||  assigned; const timeScore = hours ? Math.max (40, 100 - Math.min(60, hours * 2)) : 75; ret urn clamp(Math.round(avg([ratio(done, assigne d), ratio(done, target), ratio(approved, Math .max(1, done)), timeScore]))); }
function cal cEffectiveness(nonCompliant: number, observat ions: any[], responses: any[]) { const divers ity = unique(observations.map((o) => o.respon se?.checklistItem?.mainSection).filter(Boolea n)).length; return clamp(Math.round(avg([nonC ompliant ? Math.min(100, 55 + nonCompliant *  8) : 55, Math.min(100, diversity * 20), ratio (responses.filter((r) => r.checklistItem?.reg ulatoryReference).length, Math.max(1, respons es.length)), ratio(observations.filter((o) =>  (o.correctiveAction ?? o.response?.correctiv eAction ?? "").length >= 12).length, Math.max (1, observations.length))]))); }
function bui ldWeeklyTrend(links: any[]) { return links.ma p((link) => { const total = link.tasks.length ; const done = link.tasks.filter((task: any)  => task.status === "COMPLETED").length; retur n { name: link.week?.name ?? "-", value: rati o(done, total) }; }).slice(-8); }
function co mmonNotes(observations: any[]) { const counts  = new Map<string, number>(); observations.fo rEach((o) => { const text = (o.note ?? o.resp onse?.inspectorNote ?? "").trim(); if (text)  counts.set(text, (counts.get(text) ?? 0) + 1) ; }); return [...counts.entries()].sort((a, b ) => b[1] - a[1]).slice(0, 5).map(([text, cou nt]) => ({ text, count })); }
function sortRo ws(rows: InspectorPerformance[], sort = "over allScore", dir = "desc") { const key = sort a s keyof InspectorPerformance; return [...rows ].sort((a, b) => { const av = a[key] as any;  const bv = b[key] as any; const result = type of av === "string" ? av.localeCompare(String( bv), "ar") : Number(av ?? 0) - Number(bv ?? 0 ); return dir === "asc" ? result : -result; } ); }
function isFacilityComplete(f: any) { re turn Boolean(f?.name && f?.location && f?.cit y && f?.district && f?.classification && f?.s ecuritySensitivity && f?.representativeName & & f?.contactNumber && f?.visitDate && f?.star tedAt && f?.endedAt); }
function ratingLabel( score: number) { if (score >= 90) return "م� �تاز"; if (score >= 80) return "جيد ج� �ًا"; if (score >= 70) return "جيد"; if  (score >= 60) return "يحتاج تحسين";  return "يحتاج متابعة"; }
function  ratingTone(score: number) { if (score >= 80)  return "success"; if (score >= 70) return "s ecurity"; if (score >= 60) return "warning";  return "danger"; }
function countAudit(logs:  any[], words: string[]) { return logs.filter( (log) => words.some((word) => `${log.operatio nType} ${log.description}`.includes(word))).l ength; }
function latestDate(values: any[]) {  const dates = values.filter(Boolean).map((v)  => new Date(v)).filter((d) => !Number.isNaN( d.valueOf())); return dates.length ? new Date (Math.max(...dates.map((d) => d.valueOf())))  : null; }
function sameMonth(value: Date | st ring, month: string) { return new Date(value) .toISOString().slice(0, 7) === month; }
funct ion isRecent(value: Date | string, days: numb er) { return Date.now() - new Date(value).val ueOf() <= days * 24 * 60 * 60 * 1000; }
funct ion diffHours(start?: Date | string | null, e nd?: Date | string | null) { if (!start || !e nd) return 0; return Math.max(0, (new Date(en d).valueOf() - new Date(start).valueOf()) / 3 6e5); }
function avg(values: number[]) { cons t safe = values.filter((v) => Number.isFinite (v)); return safe.length ? Math.round((safe.r educe((s, v) => s + v, 0) / safe.length) * 10 ) / 10 : 0; }
function ratio(part: number, to tal: number) { return total ? clamp(Math.roun d((part / total) * 100)) : 0; }
function sum( rows: any[], key: string) { return rows.reduc e((total, row) => total + Number(row[key] ??  0), 0); }
function unique<T>(items: T[]) { re turn [...new Set(items)]; }
function clamp(va lue: number) { return Math.max(0, Math.min(10 0, value)); } 