import { notFound } from "next/navigation";
import { ArrowRight, Building2, CheckCircle2, Clock, MapPin } from "lucide-react";
import { Badge, Card, SecondaryButton } from "@/components/ui";
import { LineTrendChart } from "@/components/charts";
import { arDateTime, pct } from "@/lib/format";
import { getPerformanceContext } from "@/lib/performance";

export default async function InspectorPerformanceDetail({ params }: { params: Promise<{ inspectorId: string }> }) {
  const { inspectorId } = await params;
  const context = await getPerformanceContext({ inspectorId });
  const row = context.rows[0];
  if (!row) notFound();
  const strengths = [row.productivity >= 80 ? "إنتاجية مرتفعة" : null, row.documentationQuality >= 80 ? "توثيق مكتمل وواضح" : null, row.operationalCommitment >= 80 ? "التزام تشغيلي جيد" : null, row.regulatoryEffectiveness >= 80 ? "فاعلية رقابية عالية" : null].filter(Boolean);
  const improvements = [row.lateTasks > 0 ? "معالجة المهام المتأخرة" : null, row.documentationQuality < 70 ? "رفع جودة الملاحظات والمرفقات" : null, row.incompleteReports > 0 ? "إغلاق المسودات غير المكتملة" : null, row.regulatoryEffectiveness < 70 ? "تحسين ربط الملاحظات بالمعايير" : null].filter(Boolean);

  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 rounded-xl border border-security/10 bg-white/85 p-5 md:flex-row md:items-end"><div><SecondaryButton href="/admin/performance" className="mb-3 gap-2"><ArrowRight className="h-4 w-4" /> رجوع للمؤشرات</SecondaryButton><p className="text-sm font-bold text-security">تفاصيل الفاحص</p><h1 className="mt-1 text-2xl font-black text-official">{row.name}</h1><p className="mt-2 text-sm text-muted">{row.employeeNumber} · {row.department}</p></div><div><Badge tone={row.ratingTone}>{row.rating}</Badge><div className="mt-2 text-2xl font-black text-official">{row.overallScore}/100</div></div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="المهام المنجزة" value={`${row.completedTasks}/${row.assignedTasks}`} /><Metric label="المهام المتأخرة" value={row.lateTasks} tone="danger" /><Metric label="التقارير المعتمدة" value={row.approvedReports} tone="success" /><Metric label="متوسط زمن الفحص" value={`${row.avgInspectionHours} ساعة`} /></div>
    <div className="grid gap-6 xl:grid-cols-3"><Score title="الإنتاجية" value={row.productivity} /><Score title="جودة التوثيق" value={row.documentationQuality} /><Score title="الالتزام التشغيلي" value={row.operationalCommitment} /><Score title="الفاعلية الرقابية" value={row.regulatoryEffectiveness} /><Card className="xl:col-span-2"><h2 className="mb-4 text-base font-black text-official">تطور الأداء حسب الأسابيع</h2><LineTrendChart data={row.weeklyTrend.length ? row.weeklyTrend : [{ name: "لا توجد بيانات", value: 0 }]} /></Card></div>
    <div className="grid gap-6 xl:grid-cols-3"><InfoCard icon={CheckCircle2} title="نقاط القوة" items={strengths.length ? strengths as string[] : ["لا توجد نقاط قوة كافية بعد"]} /><InfoCard icon={Clock} title="نقاط التحسين" items={improvements.length ? improvements as string[] : ["لا توجد ملاحظات تحسين حالية"]} /><InfoCard icon={MapPin} title="المدن التي عمل عليها" items={row.cities.length ? row.cities : ["غير متوفر"]} /><InfoCard icon={Building2} title="أنواع المنشآت" items={row.facilityTypes.length ? row.facilityTypes : ["غير متوفر"]} /><Card className="xl:col-span-2"><h2 className="mb-4 text-base font-black text-official">الملاحظات الأكثر تكرارًا</h2><div className="grid gap-2">{row.commonNotes.length ? row.commonNotes.map((note) => <div key={note.text} className="rounded-lg border border-slate-200 bg-soft p-3"><div className="text-sm text-official">{note.text}</div><div className="mt-1 text-xs font-bold text-muted">تكررت {note.count} مرة</div></div>) : <p className="text-sm text-muted">لا توجد ملاحظات مسجلة.</p>}</div></Card></div>
    <Card><h2 className="mb-4 text-base font-black text-official">ملخص تفصيلي</h2><div className="grid gap-3 md:grid-cols-4"><Small label="نسبة الإنجاز" value={pct(row.completionRate)} /><Small label="متوسط المطابقة" value={pct(row.avgCompliance)} /><Small label="غير مطابق مكتشف" value={row.nonCompliantItems} /><Small label="الملاحظات" value={row.notesCount} /><Small label="المرفقات" value={row.attachmentsCount} /><Small label="حفظ المسودات" value={row.draftSaves} /><Small label="تعديلات قبل الاعتماد" value={row.reportEdits} /><Small label="تحقق فاشل" value={row.failedVerifications} /><Small label="آخر نشاط" value={arDateTime(row.lastActivity)} /></div></Card>
  </div>;
}
function Metric({ label, value, tone = "security" }: { label: string; value: string | number; tone?: "security" | "success" | "danger" }) { const color = tone === "success" ? "text-success bg-success/10 border-success/20" : tone === "danger" ? "text-danger bg-danger/10 border-danger/20" : "text-security bg-security/7 border-security/15"; return <Card className="p-4"><div className="text-sm text-muted">{label}</div><div className={`mt-3 inline-flex rounded-lg border px-3 py-2 text-base font-black ${color}`}>{value}</div></Card>; }
function Score({ title, value }: { title: string; value: number }) { return <Card><div className="flex items-center justify-between"><h2 className="text-base font-black text-official">{title}</h2><span className="font-black text-security">{pct(value)}</span></div><div className="mt-3 h-2 rounded-full bg-soft"><span className="block h-full rounded-full bg-security" style={{ width: `${value}%` }} /></div></Card>; }
function InfoCard({ icon: Icon, title, items }: { icon: typeof CheckCircle2; title: string; items: string[] }) { return <Card><div className="mb-3 flex items-center gap-2"><Icon className="h-5 w-5 text-security" /><h2 className="text-base font-black text-official">{title}</h2></div><ul className="space-y-2 text-sm text-muted">{items.map((item) => <li key={item}>{item}</li>)}</ul></Card>; }
function Small({ label, value }: { label: string; value: string | number }) { return <div className="rounded-lg border border-slate-200 bg-soft p-3"><div className="text-xs text-muted">{label}</div><div className="mt-1 font-black text-official">{value}</div></div>; }