import { Badge, Card, SecondaryButton, inputClass } from "@/components/ui";
import { arDateTime } from "@/lib/format";
import { prisma } from "@/lib/prisma";

export default async function AuditPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; type?: string }> }) {
  const p = await searchParams;
  const logs = await prisma.auditLog.findMany({ orderBy: { createdAt: "desc" }, take: 300 });
  const filtered = logs.filter((l) => (!p.q || l.actorName?.includes(p.q) || l.facilityName?.includes(p.q) || l.taskId?.includes(p.q)) && (!p.status || l.status === p.status) && (!p.type || l.operationType.includes(p.type)));
  return <div className="space-y-6"><div><h1 className="text-3xl font-black text-official">سجل التدقيق</h1><p className="mt-2 text-muted">توثيق جميع العمليات المهمة والناجحة والفاشلة داخل النظام.</p></div><Card><form className="mb-5 grid gap-3 md:grid-cols-4"><input name="q" className={inputClass} placeholder="الفاحص، المهمة، المنشأة"/><input name="type" className={inputClass} placeholder="نوع العملية"/><select name="status" className={inputClass}><option value="">كل الحالات</option><option value="SUCCESS">ناجحة</option><option value="FAILED">فاشلة</option></select><SecondaryButton type="submit">فلترة</SecondaryButton></form><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-muted"><th className="p-3 text-right">رقم العملية</th><th className="p-3 text-right">نوع العملية</th><th className="p-3 text-right">المستخدم</th><th className="p-3 text-right">التاريخ والوقت</th><th className="p-3 text-right">رقم المهمة</th><th className="p-3 text-right">المنشأة</th><th className="p-3 text-right">IP</th><th className="p-3 text-right">الوصف</th><th className="p-3 text-right">الحالة</th></tr></thead><tbody>{filtered.map((l, i) => <tr key={l.id} className="border-b last:border-0"><td className="p-3">{i + 1}</td><td className="p-3 font-bold">{l.operationType}</td><td className="p-3">{l.actorName ?? "-"}<br/><span className="text-xs text-muted">{l.employeeNumber ?? ""}</span></td><td className="p-3">{arDateTime(l.createdAt)}</td><td className="p-3">{l.taskId ?? "-"}</td><td className="p-3">{l.facilityName ?? "-"}</td><td className="p-3">{l.ipAddress ?? "-"}</td><td className="p-3">{l.description}</td><td className="p-3"><Badge tone={l.status === "SUCCESS" ? "success" : "danger"}>{l.status === "SUCCESS" ? "ناجحة" : "فاشلة"}</Badge></td></tr>)}</tbody></table></div></Card></div>;
}
